clc; close all; clear all

load nearWallData.mat

%% Plots
num_vec = 1:8;
cv = -((num_vec-1)/7 - 1);
l = 1.3;
m = 9;


%% Thrust Plots
figure
set(gcf, 'Units', 'centimeters');
afFigurePosition = [1 1 20 15];
set(gcf, 'Position', afFigurePosition);
set(gcf, 'PaperPositionMode', 'auto')

hold on
plot(k, Ct_d20_A25, 'd-', 'Color', [cv(1) 0 (1 - cv(1))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d30_A25, '*-', 'Color', [cv(2) 0 (1 - cv(2))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d40_A25, '^-', 'Color', [cv(3) 0 (1 - cv(3))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d50_A25, 'v-', 'Color', [cv(4) 0 (1 - cv(4))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d60_A25, '<-', 'Color', [cv(5) 0 (1 - cv(5))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d70_A25, 'x-', 'Color', [cv(6) 0 (1 - cv(6))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d80_A25, 's-', 'Color', [cv(7) 0 (1 - cv(7))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_free_A25, 'd-', 'Color', [cv(8) 0 (1 - cv(8))], 'LineWidth', l, 'MarkerSize', m)
hold off

axis([4 12 0 1.5])
set(gca, 'FontName', 'Times', 'FontSize', 24)
set(gca, 'Units', 'normalized', 'Position', [0.15 0.2 0.8 0.7]);

xlabel('$$k$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [0.5 -0.15], ...
    'Interpreter', 'LaTex');

ylabel('$$C_T$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [-0.12 0.45], ...
    'Interpreter', 'LaTex');

title('A = 2.5cm', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Interpreter', 'LaTex');

figure
set(gcf, 'Units', 'centimeters');
afFigurePosition = [1 1 20 15];
set(gcf, 'Position', afFigurePosition);
set(gcf, 'PaperPositionMode', 'auto')

hold on
plot(k, Ct_d20_A20, 'd-', 'Color', [cv(1) 0 (1 - cv(1))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d30_A20, '*-', 'Color', [cv(2) 0 (1 - cv(2))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d40_A20, '^-', 'Color', [cv(3) 0 (1 - cv(3))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d50_A20, 'v-', 'Color', [cv(4) 0 (1 - cv(4))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d60_A20, '<-', 'Color', [cv(5) 0 (1 - cv(5))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d70_A20, 'x-', 'Color', [cv(6) 0 (1 - cv(6))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d80_A20, 's-', 'Color', [cv(7) 0 (1 - cv(7))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_free_A20, 'd-', 'Color', [cv(8) 0 (1 - cv(8))], 'LineWidth', l, 'MarkerSize', m)
hold off

axis([4 12 0 0.9])
set(gca, 'FontName', 'Times', 'FontSize', 24)
set(gca, 'Units', 'normalized', 'Position', [0.15 0.2 0.8 0.7]);

xlabel('$$k$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [0.5 -0.15], ...
    'Interpreter', 'LaTex');

ylabel('$$C_T$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [-0.12 0.45], ...
    'Interpreter', 'LaTex');

title('A = 2.0cm', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Interpreter', 'LaTex');

figure
set(gcf, 'Units', 'centimeters');
afFigurePosition = [1 1 20 15];
set(gcf, 'Position', afFigurePosition);
set(gcf, 'PaperPositionMode', 'auto')

hold on
plot(k, Ct_d20_A15, 'd-', 'Color', [cv(1) 0 (1 - cv(1))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d30_A15, '*-', 'Color', [cv(2) 0 (1 - cv(2))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d40_A15, '^-', 'Color', [cv(3) 0 (1 - cv(3))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d50_A15, 'v-', 'Color', [cv(4) 0 (1 - cv(4))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d60_A15, '<-', 'Color', [cv(5) 0 (1 - cv(5))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d70_A15, 'x-', 'Color', [cv(6) 0 (1 - cv(6))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_d80_A15, 's-', 'Color', [cv(7) 0 (1 - cv(7))], 'LineWidth', l, 'MarkerSize', m)
plot(k, Ct_free_A15, 'd-', 'Color', [cv(8) 0 (1 - cv(8))], 'LineWidth', l, 'MarkerSize', m)
hold off

axis([4 12 0 0.5])
set(gca, 'FontName', 'Times', 'FontSize', 24)
set(gca, 'Units', 'normalized', 'Position', [0.15 0.2 0.8 0.7]);

xlabel('$$k$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [0.5 -0.15], ...
    'Interpreter', 'LaTex');

ylabel('$$C_T$$', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Units', 'Normalize', ...
    'Position', [-0.12 0.45], ...
    'Interpreter', 'LaTex');

title('A = 1.5cm', ...
    'FontName', 'Times', ...
    'FontUnit', 'points', ...
    'FontSize', 28, ...
    'FontWeight', 'normal', ...
    'Rotation', 0, ...
    'Interpreter', 'LaTex');